### ISSUE TITLE
After reinstalling, PROS searches the wrong location for githubreleases.pyc

### ISSUE THREAD

**Issue by ghost** [purduesigbots/pros-cli2#20]
#### Expected Behavior:
PROS will search _\<installation-dir\>\cli-64_ for _githubreleases.pyc_
#### Actual Behavior:
PROS searches _\<first-ever-installation-dir\>\cli-64_ for _githubreleases.pyc_
#### Steps to reproduce:
Install PROS somewhere, uninstall PROS, and reinstall PROS in a location different from the original one
#### System information:
Operating System: Windows

PROS Version: 2.1.6

#### Additional Information
Editing _%appdata%\PROS\cli.pros_ manually with the correct location of _githubreleases.pyc_ fixes the issue

It seems as though Cody was experiencing a similar issue [here](https://github.com/purduesigbots/pros-atom/issues/17#issuecomment-264914167).

**Comment by edjubuh** [comment]
You may also delete _cli.pros_. For the moment, this is intentional behavior as you're supposed to be able to provide your own registrars/depot providers. A better solution in the future would be to detect (https://github.com/purduesigbots/pros-cli/blob/master/prosconductor/providers/utils.py#L16) if the provided path is absolute, and if not, use a relative path based on the installation directory of the CLI.

**Comment by edjubuh** [comment]
This was fixed for Windows installers in the latest 2.4.3 release (https://github.com/purduesigbots/pros-cli/pull/24/files#diff-db0b5c399e38d173006a84abe8520992)
