### ISSUE TITLE
Jenkins compilations possible?

### ISSUE THREAD

**Issue by connor557** [purduesigbots/pros-cli2#26]
#### Expected Behavior:
Sucessful compilation on schedule using jenkins.

#### Actual Behavior:
Many random errors, all fixed by installing various wheels from pypi.
Error on import cx_Freeze, so far unsolved.

Jenkins log:
Started by user Connor O'Brien
Building in workspace /sbbs/web/root/files/vex/pros-cli
[pros-cli] $ /bin/sh -xe /tmp/hudson4564472934220571624.sh
+ python build.py build -d build/
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE

#### Steps to reproduce:
Using Jenkins, run:
python3 setup.py build
python3 setup.py sdist/bdist/bdist_rpm 

#### System information:
Operating System:
Red Hat 6 Hardened

PROS Version: (run `pros --version`)
None, reason why I'm building this compiler.

#### Additional Information
To reproduce error, must build on Jenkins.
Red Hat shell does not error when running commands in bash.

#### Screenshots/Output Dumps/Stack Traces
Traceback (most recent call last):
  File "build.py", line 2, in <module>
    from cx_Freeze import Executable, setup
ImportError: No module named cx_Freeze

**Comment by edjubuh** [comment]
`build.py` is used to create the Windows executables without depending on Python to be installed. The expected installation method for Linux and macOS is to use the universal pip wheels. cx_Freeze isn't included in `requirements.txt` because that would make it a requirement for every pros-cli pip user to install cx_Freeze, even if they have no intention of building a frozen executable. As you can see in our Windows build process, we grab cx_Freeze and install "manually" (note we do it from source because there are some fixes for Python 3.5+ that weren't yet released).

Also, SIGBots uses Jenkins to automate releases and builds. We do not have any plans to support community building with Jenkins as each Jenkins server tends to be unique.

If you're still having issues, feel free to reopen the issue however we won't make or accept any changes to the Jenkinsfile

**Comment by connor557** [comment]
Yes. I found this out about build.py. My server is back to it's regularly scheduled builds, chugging out tar gzs. I also found out my python environment was a bit incomplete, fixed using pipsi/pew.
