### ISSUE TITLE
"PROS CLI was not found on your PATH!" upon fresh installation

### ISSUE THREAD

**Issue by Aponthis** [purduesigbots/pros-cli2#38]
#### Expected Behavior: 
PROS package for Atom installs without issue

#### Actual Behavior: 
![screenshot from 2017-06-20 14-50-10](https://user-images.githubusercontent.com/13190468/27357970-4efdd08a-55c9-11e7-8ea9-f1dfb7c982cd.png)

#### Steps to reproduce:

-Install Atom
-Install PROS package and all dependencies that are prompted

#### System information:
Operating System:  Ubuntu 16.04.2 LTS
8 GB of RAM, 1 TB hard drive, any other applicable specs can be given if needed

PROS Version: (run `pros --version`)

Plugin is on 0.7.0

`pros --version` says command not found

#### Additional Information

I have tried clicking "restart." A restart does not fix this issue. I also completely reinstalled the PROS package and then Atom, but neither worked.

**Comment by edjubuh** [comment]
Hi @Aponthis, thanks for using PROS!

The PROS plugin for Atom does not install the CLI or PROS toolchain. Our install script [here](https://github.com/purduesigbots/pros/releases/download/2.11.1/pros-install_ubuntu.sh) will do it all for you. However, since you're already most of the way there it may be quicker to install the packages manually.

The following should be sufficient:
```
apt install git clang gcc-arm-none-eabi python3 python3-pip
pip3 install pros-cli
```

**Comment by Aponthis** [comment]
It was sufficient! Thank you.
