### ISSUE TITLE
Conductor does not delete files and folders when they are removed from a library

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros-cli2#51]
When upgrading a library, old files which are removed in the newer library version remain after the upgrade is done. These files should of course be removed.

For example, install OkapiLib 0.4.3 and upgrade to 0.5.0. Motion profile -related files stick around.

**Comment by edjubuh** [comment]
That's not some behavior we want - let me give an example.

Today, the PROS kernel distributes a few template files that we expect every user to modify: `opcontrol.c`, `autonomous.c`, and `init.c`. Let's say we decide for 2.13.0 we're going to now call `init.c` `initialize.c`. We shouldn't delete user's `init.c` and replace it with a blank `initialize.c` - they may have touched it (as they should have)!

However, the CLI does support this sort of operation by including files in the `remove_files` field where you can explicitly tell the CLI to delete files. You'll want to modify your `template.mk` to include:

`--ignore include/okapilib/motion_profiles.h --ignore include/okapilib/other_file.h` and so on line 18. For now, I'll keep the documentation as is, but future template makefiles will make that customizable.

**Comment by Octogonapus** [comment]
Ah, ok. Yes I was thinking about various ways to implement this without the problems you brought up. I'll just be mindful of this in the future.

**Comment by edjubuh** [comment]
With PROS CLI 3.0, we're not leaving out reimplementing most aspects of the way conductor works based on how users have been using it. One option I thought of could be explicitly describing files library owners expect users to be able to modify. I think that might make more sense because usually those files don't change names.

In such a case, we can just have one field `user_modifiable` which would never be deleted. During fresh install, all files are copied. During upgrade, all files in the old template except those described by `user_modifiable` are deleted, and the new ones are copied in. 

My biggest concern with this method would be reconciling issues when a user doesn't have the old version downloaded on their computer, but we could circumvent that by adding a list of all files added by the template to the `project.pros` file.
